project_id = "yhxoihyjtcgulnfipqej"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
image_transformation_enabled = true

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[edge_functions]
enabled = true
port = 54327

[analytics]
enabled = false
port = 54328
vector_port = 54329
gql_port = 54330

[functions.test-vindi-connection]
verify_jwt = true

[functions.generate-payment-link]
verify_jwt = true

[functions.refresh-payment-statuses]
verify_jwt = true

[functions.get-api-settings]
verify_jwt = true

[functions.update-api-settings]
verify_jwt = true

[functions.notify-external-api]
verify_jwt = true

[functions.get-user-settings]
verify_jwt = true

[functions.update-user-settings]
verify_jwt = true

[functions.mapbox-proxy]
verify_jwt = false

[functions.process-vindi-payment]
verify_jwt = false

[functions.processar-importacao-lote]
verify_jwt = true

[functions.send-franchise-invite]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.secure-checkout-validation]
verify_jwt = false

[functions.process-subscription-payment]
verify_jwt = false

[functions.vindi-webhook]
verify_jwt = false

[functions.vindi-encrypt-card]
verify_jwt = false

[functions.vindi-hosted-customer]
verify_jwt = false

[functions.vindi-hosted-subscription]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = true

[functions.transparent-checkout-payment]
verify_jwt = true

[functions.vindi-transparent-checkout]
verify_jwt = false